/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vemaproject;
import javax.swing.JOptionPane;
/**
 *
 * @author davidobiangnzue
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        waterRB = new javax.swing.JRadioButton();
        iceteaRB = new javax.swing.JRadioButton();
        pizzaRB = new javax.swing.JRadioButton();
        sandwichRB = new javax.swing.JRadioButton();
        donutRB = new javax.swing.JRadioButton();
        cokeRB = new javax.swing.JRadioButton();
        donutTF = new javax.swing.JTextField();
        cokeTF = new javax.swing.JTextField();
        pizzaTF = new javax.swing.JTextField();
        sandwichTF = new javax.swing.JTextField();
        waterTF = new javax.swing.JTextField();
        iceteaTF = new javax.swing.JTextField();
        purchasebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        money = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        moneyTF = new javax.swing.JTextField();
        changeTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Vending Machine");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select an Item"));

        waterRB.setText("Water $1,00");
        waterRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterRBActionPerformed(evt);
            }
        });

        iceteaRB.setText("Ice Tea $1,25");
        iceteaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iceteaRBActionPerformed(evt);
            }
        });

        pizzaRB.setText("Pizza $3,00");
        pizzaRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaRBActionPerformed(evt);
            }
        });

        sandwichRB.setText("Sandwich $2,50");
        sandwichRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandwichRBActionPerformed(evt);
            }
        });

        donutRB.setText("Donut $0,90");
        donutRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donutRBActionPerformed(evt);
            }
        });

        cokeRB.setText("Coke $1,50");
        cokeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeRBActionPerformed(evt);
            }
        });

        donutTF.setEditable(false);
        donutTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donutTFActionPerformed(evt);
            }
        });

        cokeTF.setEditable(false);

        waterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(iceteaRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iceteaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(sandwichRB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waterRB)
                        .addGap(18, 18, 18)
                        .addComponent(waterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(pizzaRB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pizzaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donutRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donutTF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sandwichTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cokeRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cokeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waterRB)
                    .addComponent(pizzaRB)
                    .addComponent(donutRB)
                    .addComponent(donutTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pizzaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iceteaRB)
                    .addComponent(sandwichRB)
                    .addComponent(cokeRB)
                    .addComponent(cokeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sandwichTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iceteaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        purchasebtn.setText("Purchase");
        purchasebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasebtnActionPerformed(evt);
            }
        });

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        money.setText("Insert Money :");

        change.setText("Change :");

        moneyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTFActionPerformed(evt);
            }
        });

        changeTF.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(purchasebtn)
                        .addGap(46, 46, 46)
                        .addComponent(clearbtn)
                        .addGap(55, 55, 55)
                        .addComponent(cancelbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(money)
                            .addComponent(change))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moneyTF, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(changeTF))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(money)
                    .addComponent(moneyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(change)
                    .addComponent(changeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchasebtn)
                    .addComponent(clearbtn)
                    .addComponent(cancelbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waterRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterRBActionPerformed
        // changing radio buttons to select only one
        
        if(waterRB.isSelected()){
           iceteaRB.setSelected(false);
           cokeRB.setSelected(false);
           donutRB.setSelected(false);
           pizzaRB.setSelected(false);
           sandwichRB.setSelected(false);
           
        }
    }//GEN-LAST:event_waterRBActionPerformed

    private void moneyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTFActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // cancels selections
        
        System.exit(0);
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // clears all selections and textfields
        waterRB.setSelected(false);
        iceteaRB.setSelected(false);
        cokeRB.setSelected(false);
        donutRB.setSelected(false);
        pizzaRB.setSelected(false);
        sandwichRB.setSelected(false);
        moneyTF.setText(" ");
        changeTF.setText(" ");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void pizzaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaRBActionPerformed
        // TODO add your handling code here:
        if(pizzaRB.isSelected()){
           iceteaRB.setSelected(false);
           cokeRB.setSelected(false);
           donutRB.setSelected(false);
           waterRB.setSelected(false);
           sandwichRB.setSelected(false);
           
        }
        
        
        
    }//GEN-LAST:event_pizzaRBActionPerformed

    private void donutRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donutRBActionPerformed
        // TODO add your handling code here:
        if(donutRB.isSelected()){
           iceteaRB.setSelected(false);
           cokeRB.setSelected(false);
           waterRB.setSelected(false);
           pizzaRB.setSelected(false);
           sandwichRB.setSelected(false);
           
        }
        
        
        
        
    }//GEN-LAST:event_donutRBActionPerformed

    private void iceteaRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iceteaRBActionPerformed
        // TODO add your handling code here:
        if(iceteaRB.isSelected()){
           waterRB.setSelected(false);
           cokeRB.setSelected(false);
           donutRB.setSelected(false);
           pizzaRB.setSelected(false);
           sandwichRB.setSelected(false);
           
        }
        
        
        
        
    }//GEN-LAST:event_iceteaRBActionPerformed

    private void sandwichRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwichRBActionPerformed
        // TODO add your handling code here:
        if(sandwichRB.isSelected()){
           iceteaRB.setSelected(false);
           cokeRB.setSelected(false);
           donutRB.setSelected(false);
           pizzaRB.setSelected(false);
           waterRB.setSelected(false);
           
        }
        
        
    }//GEN-LAST:event_sandwichRBActionPerformed

    private void cokeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeRBActionPerformed
        // TODO add your handling code here:
        if(cokeRB.isSelected()){
           iceteaRB.setSelected(false);
           waterRB.setSelected(false);
           donutRB.setSelected(false);
           pizzaRB.setSelected(false);
           sandwichRB.setSelected(false);
           
        }
        
        
    }//GEN-LAST:event_cokeRBActionPerformed

    private void purchasebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasebtnActionPerformed
        // this pays for your purchase if you have enough money
        double money = 0;
        
        money = Double.parseDouble(moneyTF.getText());
        
         if(waterRB.isSelected()){
            money=money -1.00;
         } else if(iceteaRB.isSelected()){
           money= money -1.25;
           }else if(pizzaRB.isSelected()){
           money= money -3.00;
           }else if(sandwichRB.isSelected()){
           money= money -2.50;
           }else if(donutRB.isSelected()){
           money= money -0.90;
           }else if(cokeRB.isSelected()){
           money= money -1.50;
           }
         
         if(money <0){
            JOptionPane.showMessageDialog(rootPane, "Sorry You Do Not Have Enough Money");
           }else {
            changeTF.setText(Double.toString(money));
         }
    }//GEN-LAST:event_purchasebtnActionPerformed

    private void donutTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donutTFActionPerformed
        //checks the stock of donuts
         int stock = 5;
         stock = Integer.parseInt(donutTF.getText());
         donutTF.setText(String.valueOf(stock));
         //System.out.println(stock);
         if(donutRB.isSelected()){
         donutTF.setText(String.valueOf(stock));    
         stock = stock-1 ; 
         System.out.println(stock);
         }
        
    }//GEN-LAST:event_donutTFActionPerformed

    private void waterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waterTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel change;
    private javax.swing.JTextField changeTF;
    private javax.swing.JButton clearbtn;
    private javax.swing.JRadioButton cokeRB;
    private javax.swing.JTextField cokeTF;
    private javax.swing.JRadioButton donutRB;
    private javax.swing.JTextField donutTF;
    private javax.swing.JRadioButton iceteaRB;
    private javax.swing.JTextField iceteaTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel money;
    private javax.swing.JTextField moneyTF;
    private javax.swing.JRadioButton pizzaRB;
    private javax.swing.JTextField pizzaTF;
    private javax.swing.JButton purchasebtn;
    private javax.swing.JRadioButton sandwichRB;
    private javax.swing.JTextField sandwichTF;
    private javax.swing.JRadioButton waterRB;
    private javax.swing.JTextField waterTF;
    // End of variables declaration//GEN-END:variables
}
